name: e_commerce_app
description: B2C

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^4.0.0
  provider: ^6.0.5
  ### we don't use last version of collection because flutter test depend on this version
  collection: ^1.17.1
  http: ^1.1.0
  connectivity_plus: ^4.0.2
  connectivity: ^3.0.6
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.3
  badges: ^3.1.1
  sqflite: ^2.2.8+1
  path_provider: ^2.0.14
  sizer: ^2.0.15
  google_sign_in: ^6.1.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.0
  firebase_messaging: ^14.6.5
  flutter_otp_text_field: ^1.1.1
  lottie: ^2.4.0
  device_preview: ^1.1.0
  flutter_localization:
  flutter_localizations:
    sdk : flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie_files/
    - assets/lang/
    - assets/images/
    - assets/images/category/
    - assets/images/onboarding/
    - assets/images/login_process/
    - assets/images/icons/
    - assets/images/promo/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Times
      fonts:
        - asset: assets/fonts/Times_New_Roman/times-new-roman.ttf
        - asset: assets/fonts/Times_New_Roman/times-new-roman-bold.ttf
        - asset: assets/fonts/Times_New_Roman/times-new-roman-bold-italic.ttf
        - asset: assets/fonts/Times_New_Roman/times-new-roman-italic.ttf
          weight: 400
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Arabic
      fonts:
        - asset: assets/fonts/alfont_com_UthmanicHafs_V20.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
